# Generated by Django 5.2.4 on 2025-07-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('sleeve', models.CharField(max_length=100)),
                ('neckline', models.CharField(max_length=100)),
                ('fit', models.CharField(max_length=100)),
                ('occasion', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
            ],
        ),
    ]
